"""migracao_final_para_render

Revision ID: 501bccf1f76a
Revises: 8ac8fb055557
Create Date: 2025-11-17 13:16:08.474625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '501bccf1f76a'
down_revision: Union[str, None] = '8ac8fb055557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. CRIAÇÃO DE NOVAS TABELAS: Clientes e Compras
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    
    op.create_table('compra_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_compra', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compra_clientes_id'), 'compra_clientes', ['id'], unique=False)
    
    op.create_table('compra_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compra_clientes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compra_itens_id'), 'compra_itens', ['id'], unique=False)
    
    # 2. DELEÇÃO DE ESTRUTURAS ANTIGAS: Drop de Foreign Keys **PRIORITÁRIO**
    
    # A. Drop de TODAS as Foreign Keys que apontam para as tabelas a serem excluídas (Projetos e Gerenciamentos)
    
    # CONSTRAINT QUE CAUSOU O ÚLTIMO ERRO (movimentacoes -> projetos)
    op.drop_constraint('movimentacoes_projeto_id_fkey', 'movimentacoes', type_='foreignkey')

    # Constraints que causaram erros anteriores (checklists -> itens, acoes, usuarios)
    op.drop_constraint('gerenciamento_checklists_item_id_fkey', 'gerenciamento_checklists', type_='foreignkey')
    op.drop_constraint('gerenciamento_checklists_acao_id_fkey', 'gerenciamento_checklists', type_='foreignkey')
    op.drop_constraint('gerenciamento_checklists_concluido_por_fkey', 'gerenciamento_checklists', type_='foreignkey')

    # Constraints das tabelas N:N de Projetos
    op.drop_constraint('projeto_colaboradores_projeto_id_fkey', 'projeto_colaboradores', type_='foreignkey')
    op.drop_constraint('projeto_colaboradores_usuario_id_fkey', 'projeto_colaboradores', type_='foreignkey')
    op.drop_constraint('projeto_produtos_produto_id_fkey', 'projeto_produtos', type_='foreignkey')
    op.drop_constraint('projeto_produtos_projeto_id_fkey', 'projeto_produtos', type_='foreignkey')
    
    # Constraints das tabelas de Gerenciamento (acoes, itens, permissoes)
    op.drop_constraint('gerenciamento_acoes_gerenciamento_id_fkey', 'gerenciamento_acoes', type_='foreignkey')
    op.drop_constraint('gerenciamento_itens_gerenciamento_id_fkey', 'gerenciamento_itens', type_='foreignkey')
    op.drop_constraint('gerenciamentos_criado_por_fkey', 'gerenciamentos', type_='foreignkey')
    op.drop_constraint('gerenciamento_permissoes_gerenciamento_id_fkey', 'gerenciamento_permissoes', type_='foreignkey')
    op.drop_constraint('gerenciamento_permissoes_usuario_id_fkey', 'gerenciamento_permissoes', type_='foreignkey')
    
    # Constraints da tabela Projetos principal
    op.drop_constraint('projetos_responsavel_id_fkey', 'projetos', type_='foreignkey')


    # B. Drop de Índices e Tabelas Antigas (A ordem não importa mais para FKs, mas a organização ajuda)
    
    op.drop_index(op.f('ix_gerenciamento_checklists_id'), table_name='gerenciamento_checklists')
    op.drop_table('gerenciamento_checklists')
    
    op.drop_index(op.f('ix_projeto_colaboradores_id'), table_name='projeto_colaboradores')
    op.drop_table('projeto_colaboradores')

    op.drop_index(op.f('ix_projeto_produtos_id'), table_name='projeto_produtos')
    op.drop_table('projeto_produtos')

    op.drop_index(op.f('ix_gerenciamento_permissoes_id'), table_name='gerenciamento_permissoes')
    op.drop_table('gerenciamento_permissoes')
    
    op.drop_index(op.f('ix_gerenciamento_itens_id'), table_name='gerenciamento_itens')
    op.drop_table('gerenciamento_itens')
    
    op.drop_index(op.f('ix_gerenciamento_acoes_id'), table_name='gerenciamento_acoes')
    op.drop_table('gerenciamento_acoes')
    
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_table('projetos')
    
    op.drop_index(op.f('ix_gerenciamentos_id'), table_name='gerenciamentos')
    op.drop_table('gerenciamentos')

    # 3. ALTERAÇÕES DE COLUNAS E TIPOS
    
    # Movimentacoes: (A remoção da FK já foi feita no início)
    op.drop_column('movimentacoes', 'projeto_id') 
    op.alter_column('movimentacoes', 'tipo',
                    existing_type=postgresql.ENUM('entrada', 'saida', name='tipo_enum'),
                    type_=sa.String(length=20),
                    existing_nullable=False)

    # Usuarios:
    op.alter_column('usuarios', 'nivel_acesso',
                    existing_type=postgresql.ENUM('admin', 'usuario', 'visualizacao', name='nivel_acesso_enum'),
                    type_=sa.String(length=20),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'nivel_acesso',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('admin', 'usuario', 'visualizacao', name='nivel_acesso_enum'),
               nullable=True)
    op.add_column('movimentacoes', sa.Column('projeto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('movimentacoes_projeto_id_fkey'), 'movimentacoes', 'projetos', ['projeto_id'], ['id'])
    op.alter_column('movimentacoes', 'tipo',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('entrada', 'saida', name='tipo_enum'),
               existing_nullable=False)
    op.create_table('gerenciamento_permissoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gerenciamento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pode_editar', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gerenciamento_id'], ['gerenciamentos.id'], name=op.f('gerenciamento_permissoes_gerenciamento_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('gerenciamento_permissoes_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gerenciamento_permissoes_pkey'))
    )
    op.create_index(op.f('ix_gerenciamento_permissoes_id'), 'gerenciamento_permissoes', ['id'], unique=False)
    op.create_table('projetos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('projetos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('local', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('responsavel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('planejamento', 'em_andamento', 'concluido', 'cancelado', name='status_enum'), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_atualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name='projetos_responsavel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='projetos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    op.create_table('projeto_produtos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('projeto_produtos_produto_id_fkey')),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], name=op.f('projeto_produtos_projeto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projeto_produtos_pkey')),
    sa.UniqueConstraint('projeto_id', 'produto_id', name=op.f('uq_projeto_produto'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_projeto_produtos_id'), 'projeto_produtos', ['id'], unique=False)
    op.create_table('gerenciamento_checklists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acao_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('concluido', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('concluido_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['acao_id'], ['gerenciamento_acoes.id'], name=op.f('gerenciamento_checklists_acao_id_fkey')),
    sa.ForeignKeyConstraint(['concluido_por'], ['usuarios.id'], name=op.f('gerenciamento_checklists_concluido_por_fkey')),
    sa.ForeignKeyConstraint(['item_id'], ['gerenciamento_itens.id'], name=op.f('gerenciamento_checklists_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gerenciamento_checklists_pkey'))
    )
    op.create_index(op.f('ix_gerenciamento_checklists_id'), 'gerenciamento_checklists', ['id'], unique=False)
    op.create_table('projeto_colaboradores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], name=op.f('projeto_colaboradores_projeto_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('projeto_colaboradores_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projeto_colaboradores_pkey')),
    sa.UniqueConstraint('projeto_id', 'usuario_id', name=op.f('uq_projeto_usuario'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_projeto_colaboradores_id'), 'projeto_colaboradores', ['id'], unique=False)
    op.create_table('gerenciamento_acoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gerenciamento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gerenciamento_id'], ['gerenciamentos.id'], name=op.f('gerenciamento_acoes_gerenciamento_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gerenciamento_acoes_pkey'))
    )
    op.create_index(op.f('ix_gerenciamento_acoes_id'), 'gerenciamento_acoes', ['id'], unique=False)
    op.create_table('gerenciamentos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('gerenciamentos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('criado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('publico', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], name='gerenciamentos_criado_por_fkey'),
    sa.PrimaryKeyConstraint('id', name='gerenciamentos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_gerenciamentos_id'), 'gerenciamentos', ['id'], unique=False)
    op.create_table('gerenciamento_itens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gerenciamento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gerenciamento_id'], ['gerenciamentos.id'], name=op.f('gerenciamento_itens_gerenciamento_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gerenciamento_itens_pkey'))
    )
    op.create_index(op.f('ix_gerenciamento_itens_id'), 'gerenciamento_itens', ['id'], unique=False)
    op.drop_index(op.f('ix_compra_itens_id'), table_name='compra_itens')
    op.drop_table('compra_itens')
    op.drop_index(op.f('ix_compra_clientes_id'), table_name='compra_clientes')
    op.drop_table('compra_clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
