"""Criar tabela compra_itens

Revision ID: 8ac8fb055557
Revises: 929d7c77ed34
Create Date: 2025-11-02 12:59:54.580279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8ac8fb055557'
down_revision: Union[str, None] = '929d7c77ed34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compra_clientes', 'itens')
    op.drop_constraint(op.f('compra_itens_ibfk_2'), 'compra_itens', type_='foreignkey')
    op.drop_constraint(op.f('compra_itens_ibfk_1'), 'compra_itens', type_='foreignkey')
    op.create_foreign_key(None, 'compra_itens', 'compra_clientes', ['compra_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compra_itens', type_='foreignkey')
    op.create_foreign_key(op.f('compra_itens_ibfk_1'), 'compra_itens', 'compra_clientes', ['compra_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('compra_itens_ibfk_2'), 'compra_itens', 'produtos', ['produto_id'], ['id'])
    op.add_column('compra_clientes', sa.Column('itens', mysql.JSON(), nullable=False))
    # ### end Alembic commands ###
