"""add senha_hash and cep to cliente

Revision ID: 929d7c77ed34
Revises: e33748b1cb42
Create Date: 2025-10-28 19:45:05.371699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '929d7c77ed34'
down_revision: Union[str, None] = 'e33748b1cb42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('senha_hash', sa.String(length=255), nullable=False))
    op.add_column('clientes', sa.Column('cep', sa.String(length=20), nullable=True))
    op.alter_column('compra_clientes', 'cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('compra_clientes', 'data_criacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compra_clientes', sa.Column('data_criacao', mysql.DATETIME(), nullable=True))
    op.alter_column('compra_clientes', 'cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('clientes', 'cep')
    op.drop_column('clientes', 'senha_hash')
    # ### end Alembic commands ###
