"""criação das tabelas iniciais

Revision ID: db59fe21bba0
Revises: 3d57d479ffb6
Create Date: 2025-06-21 08:33:39.629406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db59fe21bba0'
down_revision: Union[str, None] = '3d57d479ffb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nivel_acesso', sa.Enum('admin', 'usuario', 'visualizacao', name='nivel_acesso_enum'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('gerenciamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('status', sa.Float(), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gerenciamentos_id'), 'gerenciamentos', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('tabela_afetada', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('dados_antigos', sa.JSON(), nullable=True),
    sa.Column('dados_novos', sa.JSON(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo_sku', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('quantidade_minima', sa.Integer(), nullable=True),
    sa.Column('quantidade_maxima', sa.Integer(), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_codigo_sku'), 'produtos', ['codigo_sku'], unique=True)
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planejamento', 'em_andamento', 'concluido', 'cancelado', name='status_enum'), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    op.create_table('gerenciamento_acoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gerenciamento_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gerenciamento_id'], ['gerenciamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gerenciamento_acoes_id'), 'gerenciamento_acoes', ['id'], unique=False)
    op.create_table('gerenciamento_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gerenciamento_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gerenciamento_id'], ['gerenciamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gerenciamento_itens_id'), 'gerenciamento_itens', ['id'], unique=False)
    op.create_table('gerenciamento_permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gerenciamento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('pode_editar', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['gerenciamento_id'], ['gerenciamentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gerenciamento_permissoes_id'), 'gerenciamento_permissoes', ['id'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipo_enum'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False)
    op.create_table('projeto_colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'usuario_id', name='uq_projeto_usuario')
    )
    op.create_index(op.f('ix_projeto_colaboradores_id'), 'projeto_colaboradores', ['id'], unique=False)
    op.create_table('projeto_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'produto_id', name='uq_projeto_produto')
    )
    op.create_index(op.f('ix_projeto_produtos_id'), 'projeto_produtos', ['id'], unique=False)
    op.create_table('gerenciamento_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('acao_id', sa.Integer(), nullable=True),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('concluido_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acao_id'], ['gerenciamento_acoes.id'], ),
    sa.ForeignKeyConstraint(['concluido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['gerenciamento_itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gerenciamento_checklists_id'), 'gerenciamento_checklists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gerenciamento_checklists_id'), table_name='gerenciamento_checklists')
    op.drop_table('gerenciamento_checklists')
    op.drop_index(op.f('ix_projeto_produtos_id'), table_name='projeto_produtos')
    op.drop_table('projeto_produtos')
    op.drop_index(op.f('ix_projeto_colaboradores_id'), table_name='projeto_colaboradores')
    op.drop_table('projeto_colaboradores')
    op.drop_index(op.f('ix_movimentacoes_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_gerenciamento_permissoes_id'), table_name='gerenciamento_permissoes')
    op.drop_table('gerenciamento_permissoes')
    op.drop_index(op.f('ix_gerenciamento_itens_id'), table_name='gerenciamento_itens')
    op.drop_table('gerenciamento_itens')
    op.drop_index(op.f('ix_gerenciamento_acoes_id'), table_name='gerenciamento_acoes')
    op.drop_table('gerenciamento_acoes')
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_codigo_sku'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_gerenciamentos_id'), table_name='gerenciamentos')
    op.drop_table('gerenciamentos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
